import { Geist, Geist_Mono } from "next/font/google"
import { getGlobalStyles } from '@/app/services/globalStyleService'
import "./globals.css"

import Header from '@/app/components/Header'
import Footer from '@/app/components/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Hello, Next.js",
  description: "!Generated by create next app",
}

export default async function RootLayout({ children }) {

  const styleData = await getGlobalStyles()

  const globalStylesheet = styleData?.data?.globalStylesheet

  const globalStyes = styleData?.data?.globalStyes

  return (
    <html lang="en">

      <head>
        {globalStylesheet && (
          <style id="wppg-globalStylesheet"
            dangerouslySetInnerHTML={{ __html: globalStylesheet }}
          />
        )}

        {globalStyes && (
          <style id="wppg-globalStyes"
            dangerouslySetInnerHTML={{ __html: globalStyes }}
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="wp-site-blocks">

          {/* Header */}
          <Header />

          {/* Content */}
          {children}

          {/* Footer */}
          <Footer />

        </div>
      </body>
    </html>
  )
}
